resources:
- name: evening-time
  type: time
  source:
    start: 20:00
    stop: 20:05
    location: Europe/London

jobs:
- name: scambs-bins-job
  plan:
  - get: evening-time
    trigger: true

  - task: scambs-check-bin-calendar
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: frostvoid/scambs-bins
          tag: latest
      run:
        path: /bin/bash
        args:
          - -c
          - |
            cd /app
            sbt -error run